config/routes.rb
Rails.application.routes.draw do
  get 'review/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create, :new]
    resources :review, only: [:create, :new]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
   before_action :set_cocktail, only: [:show]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    @cocktail = Cocktail.find(params[:id])
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
     redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/controllers/concerns/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:show, :new, :create]
  def index
    @cocktail = Cocktail.all
    @doses = Dose.all
  end

  def show
    @dose = Dose.find(params[:id])
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    respond_to do |format|
      format.html { redirect_to cocktail_url, notice: 'Dose was successfully destroyed.' }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end

    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render "cocktails/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/cocktails/index.html.erb
<div class="banner">
    <div class="container">
      <h1>Happy Daze</h1>
      <h2>cocktail bar</h2>
      <p>You deserve a cocktail today</p>
      <%= link_to "Add your own", new_cocktail_path, class: "btn btn-light btn-lg" %>
    </div>
</div>
<br>
<div class="container">
  <div class= "row"></div>
  <h2>Our cocktail Menu</h2>
  <br>
  <div class="card-columns">
    <% @cocktails.each do |cocktail| %>
        <div class= "card" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.2)), url('https://source.unsplash.com/featured/?{drink},{cocktail}<%= (1..10000).to_a.sample %>');">
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
          </div>
          <%= link_to "View", cocktail_path(cocktail), class: 'card-link' %>
        </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Create a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= @cocktail.name %></h1>
      <%= link_to "Back to all cocktails", root_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-6">
      <%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail) %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <h3>Reviews</h3>
      <% if @cocktail.reviews.empty? %>
        <p>Be the first to let a review</p>
      <% else %>
        <ul class="list-group">
          <% @cocktail.reviews.each do |review| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <span class="badge badge-primary badge-pill">
                <% counter = 0 %>
                <% 5.times do %>
                  <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                  <% counter += 1 %>
                <% end %>
              </span>
              <%= review.content %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <%= link_to "Add a review", new_cocktail_review_path(@cocktail) %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    <div>
  </div>
</div>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/review/new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [cocktail, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>